webserver:
  container_name: nginx
  image: shridharpatil01/nginx
  ports:
    - "443:443"
  links:
    - app:app
  net: local_network
app:
  container_name: rails-app
  image: shridharpatil01/rails-app
  ports:
  - "3000:3000"
  net: local_network
