webserver:
  container_name: nginx
  build: ./nginx
  image: shridharpatil01/nginx:latest
  ports:
    - "443:443"
  links:
    - app:app
  net: local_network
app:
  container_name: rails-app
  build: ./app-code
  image:  shridharpatil01/rails-app:latest
  net: local_network