apiVersion: v1
kind: Service
metadata:
  name: rails-app-svc
  namespace: snowflake
  labels:
    app: rails-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: app-port
  selector:
    app: rails-app
