apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails-app-deployment
  namespace: snowflake
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rails-app
    spec:
      containers:
      - image: shridharpatil01/rails-app:latest
        name: rails-app
        ports: 
          - containerPort: 3000
            name: app-port
            protocol: TCP
      restartPolicy: Always
